name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRES_USER: "${{ secrets.TEST_POSTGRES_USER }}"
  POSTGRES_PASSWORD: "${{ secrets.TEST_POSTGRES_PASSWORD }}"
  POSTGRES_DB: "${{ secrets.TEST_POSTGRES_DB }}"
  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Test
      run: make test
      
    - name: Generate code coverage report
      run: make coverage
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
